#!/bin/sh
# Helper script that runs the pytorch model disco.py

# Run model with parameters from yaml config
python disco.py --config_file ./configs/TimeToDisco.yaml

# Log the output for testing
#echo $@ > output.log

# Log the output for testing
#echo python disco.py $@ >> output.log