<template>
  <div>
    <div class="row justify-content-center">
      <div class="col-lg-10 col-sm-12">
        <h1 class="text-start display-5">
          High-resolution images generated by Ai
        </h1>
        <div v-if="!isPageLoaded">
          <p class="text-start fs-5">
            {{ getText }}
            <span v-if="showCursor" class="blink">|</span>
          </p>
        </div>
        <div v-else>
          <p class="text-start fs-5">{{ textInput }}</p>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: "TypingComponent",
  data() {
    return {
      i: 0,
      textOutput: "",
      textInput:
        "We leverage an AI Image generating technique called CLIP-Guided Diffusion to allow you to create compelling and beautiful images from just text inputs. Made with love by Zen and Valar!",
    };
  },
  methods: {
    delay(ms) {
      return new Promise((resolve) => setTimeout(resolve, ms));
    },
    async setText() {
      if (this.i <= this.textInput.length) {
        this.textOutput += this.textInput.charAt(this.i);
        await this.delay(20);
        this.i++;
        this.setText();
      } else {
        sessionStorage.setItem(this.$options.name, "typingComponent");
      }
    },
  },
  computed: {
    getText() {
      return this.textOutput;
    },
    showCursor() {
      if (this.i == this.textOutput.length + 1) {
        this.$emit("set-cursor");
      }
      return this.i <= this.textOutput.length ? true : false;
    },
    isPageLoaded() {
      return sessionStorage.getItem(this.$options.name) == "typingComponent";
    },
  },
  mounted() {
    this.setText();
  },
};
</script>
