<template>
  <div>
    <h1 class="text-start mb-4">
      <strong> High-resolution images generated by Ai </strong>
    </h1>
    <p class="text-start fs-5">
      {{ getText() }}
      <span v-if="showCursor" class="blink">|</span>
    </p>
  </div>
</template>

<script>
export default {
  name: "TypingComponent",
  data() {
    return {
      i: 0,
      textOutput: "",
      textInput:
        "We leverage an AI Image generating technique called CLIP-Guided Diffusion to allow you to create compelling and beautiful images from just text inputs. Made with love by Zen and Valar!",
    };
  },
  methods: {
    getText() {
      return this.textOutput;
    },
    delay(ms) {
      return new Promise((resolve) => setTimeout(resolve, ms));
    },
    async setText() {
      if (this.i <= this.textInput.length) {
        this.textOutput += this.textInput.charAt(this.i);
        await this.delay(40);
        this.i++;
        this.setText();
      }
    },
  },
  computed: {
    showCursor() {
      if (this.i == this.textOutput.length + 1) {
        this.$emit("set-cursor");
      }
      return this.i <= this.textOutput.length ? true : false;
    },
  },
  mounted() {
    this.setText();
  },
};
</script>
