
name: Redeploy website/view/dist/ to remote server
# Git hub workflow on push to master
# Adds ssh keys to runner and redeploys local folder

on:
  push:
    branches:
      - master

jobs:
  Configure-Runner-SSH:
    runs-on: ubuntu-latest
    env: 
      SSH_AUTH_SOCK: /tmp/ssh_agent.sock
    steps:
      - name: checkout the repo
        uses: actions/checkout@v3
      - name: Configure-Runner-SSH
        run: |
          mkdir -p /home/runner/.ssh
          ssh-keyscan exia.art >> /home/runner/.ssh/known_hosts
          echo "${{ secrets.EXIA_SSH_KEY }}" > /home/runner/.ssh/github_actions
          chmod 600 /home/runner/.ssh/github_actions
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null   
          ssh-add /home/runner/.ssh/github_actions
      - name: Run script to redeploy dist folder
        run: |
          bash ./GitHubAction-Scripts/redeploy_dist
